# Generated by Django 4.2.4 on 2024-01-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='recipe_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='recipeitems',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipeitems',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='recipeitems',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipeitems',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeitems',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.recipe'),
            preserve_default=False,
        ),
    ]
